name: Validar HTML

on:
  push:
    paths:
      - "index.html"
  pull_request:
    paths:
      - "index.html"

jobs:
  htmlhint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar htmlhint
        run: npm install -g htmlhint

      - name: Validar index.html
        run: htmlhint index.html --format=stylish
